/* Do not edit. File generated by rastro_generate. */

#ifndef _RASTRO_rastro_write_functions_H_
#define _RASTRO_rastro_write_functions_H_

#include "rastro_public.h"
#include "rastro_private.h"


#endif
