/*
    Copyright (c) 1998--2006 Benhur Stein
    
    This file is part of Pajé.

    Pajé is free software; you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    Pajé is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
    for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Pajé; if not, write to the Free Software Foundation, Inc.,
	51 Franklin Street, Fifth Floor, Boston, MA 02111 USA.
*/


/* Do not edit. File generated by rastro_generate. */

#include "saida.h"

void rst_event_iwlsifcd_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int16_t w0, u_int64_t l0, u_int8_t *s0, u_int32_t i1, float f0, u_int8_t c0, double d0)
{
	rst_startevent(ptr, type<<18|0x2437);
	RST_PUT(ptr, u_int32_t, 0x27561000);
	RST_PUT(ptr, double, d0);
	RST_PUT(ptr, u_int64_t, l0);
	RST_PUT(ptr, float, f0);
	RST_PUT(ptr, u_int32_t, i0);
	RST_PUT(ptr, u_int32_t, i1);
	RST_PUT(ptr, u_int16_t, w0);
	RST_PUT(ptr, u_int8_t, c0);
	RST_PUT_STR(ptr, s0);
	rst_endevent(ptr);
}

void rst_event_lws_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0, u_int16_t w0, u_int8_t *s0)
{
	rst_startevent(ptr, type<<18|0x24510);
	RST_PUT(ptr, u_int64_t, l0);
	RST_PUT(ptr, u_int16_t, w0);
	RST_PUT_STR(ptr, s0);
	rst_endevent(ptr);
}

void rst_event_wlsfcd_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, u_int64_t l0, u_int8_t *s0, float f0, u_int8_t c0, double d0)
{
	rst_startevent(ptr, type<<18|0x2435);
	RST_PUT(ptr, u_int32_t, 0x26100000);
	RST_PUT(ptr, double, d0);
	RST_PUT(ptr, u_int64_t, l0);
	RST_PUT(ptr, float, f0);
	RST_PUT(ptr, u_int16_t, w0);
	RST_PUT(ptr, u_int8_t, c0);
	RST_PUT_STR(ptr, s0);
	rst_endevent(ptr);
}

