/*
    Copyright (c) 1998--2006 Benhur Stein
    
    This file is part of Pajé.

    Pajé is free software; you can redistribute it and/or modify it under
    the terms of the GNU Lesser General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    Pajé is distributed in the hope that it will be useful, but WITHOUT ANY
    WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
    FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public License
    for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with Pajé; if not, write to the Free Software Foundation, Inc.,
	51 Franklin Street, Fifth Floor, Boston, MA 02111 USA.
*/


/* Do not edit. File generated by rastro_generate. */

#ifndef _RASTRO_saida_H_
#define _RASTRO_saida_H_

#include "rastro.h"
#include "rst_private.h"

void rst_event_iwlsifcd_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int16_t w0, u_int64_t l0, u_int8_t *s0, u_int32_t i1, float f0, u_int8_t c0, double d0);
#define rst_event_iwlsifcd(type, i0, w0, l0, s0, i1, f0, c0, d0) rst_event_iwlsifcd_ptr(RST_PTR, type, i0, w0, l0, s0, i1, f0, c0, d0)
void rst_event_lws_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0, u_int16_t w0, u_int8_t *s0);
#define rst_event_lws(type, l0, w0, s0) rst_event_lws_ptr(RST_PTR, type, l0, w0, s0)
void rst_event_wlsfcd_ptr(rst_buffer_t *ptr, u_int16_t type, u_int16_t w0, u_int64_t l0, u_int8_t *s0, float f0, u_int8_t c0, double d0);
#define rst_event_wlsfcd(type, w0, l0, s0, f0, c0, d0) rst_event_wlsfcd_ptr(RST_PTR, type, w0, l0, s0, f0, c0, d0)

#endif
