/* Do not edit. File generated by rastro_generate. */

#ifndef _RASTRO_aky_rastro_H_
#define _RASTRO_aky_rastro_H_

#include "rastro.h"
#include "rastro_private.h"

void rst_event_i_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0);
#define rst_event_i(type, i0) rst_event_i_ptr(RST_PTR, type, i0)
void rst_event_ii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1);
#define rst_event_ii(type, i0, i1) rst_event_ii_ptr(RST_PTR, type, i0, i1)
void rst_event_iii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2);
#define rst_event_iii(type, i0, i1, i2) rst_event_iii_ptr(RST_PTR, type, i0, i1, i2)
void rst_event_iiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3);
#define rst_event_iiii(type, i0, i1, i2, i3) rst_event_iiii_ptr(RST_PTR, type, i0, i1, i2, i3)
void rst_event_iiiii_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int32_t i2, u_int32_t i3, u_int32_t i4);
#define rst_event_iiiii(type, i0, i1, i2, i3, i4) rst_event_iiiii_ptr(RST_PTR, type, i0, i1, i2, i3, i4)

#endif
