/* Do not edit. File generated by rastro. */

#include "aky_rastro.h"

/* Rastro function implementation for 'i' */
void rst_event_i_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0)
{
  rst_startevent(ptr, type<<18|0x27000);
  RST_PUT(ptr, u_int32_t, i0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'i' - fortran support */
void rst_event_i_f_( int16_t *type, int32_t* i0)
{
  rst_event_i ((u_int16_t)* type, (u_int32_t)* i0);
}

/* Rastro function implementation for 'iil' */
void rst_event_iil_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int32_t i1, u_int64_t l0)
{
  rst_startevent(ptr, type<<18|0x24770);
  RST_PUT(ptr, u_int64_t, l0);
  RST_PUT(ptr, u_int32_t, i0);
  RST_PUT(ptr, u_int32_t, i1);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'iil' - fortran support */
void rst_event_iil_f_( int16_t *type, int32_t* i0, int32_t* i1, int64_t* l0)
{
  rst_event_iil ((u_int16_t)* type, (u_int32_t)* i0, (u_int32_t)* i1, (u_int64_t)* l0);
}

/* Rastro function implementation for 'il' */
void rst_event_il_ptr(rst_buffer_t *ptr, u_int16_t type, u_int32_t i0, u_int64_t l0)
{
  rst_startevent(ptr, type<<18|0x24700);
  RST_PUT(ptr, u_int64_t, l0);
  RST_PUT(ptr, u_int32_t, i0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'il' - fortran support */
void rst_event_il_f_( int16_t *type, int32_t* i0, int64_t* l0)
{
  rst_event_il ((u_int16_t)* type, (u_int32_t)* i0, (u_int64_t)* l0);
}

/* Rastro function implementation for 'l' */
void rst_event_l_ptr(rst_buffer_t *ptr, u_int16_t type, u_int64_t l0)
{
  rst_startevent(ptr, type<<18|0x24000);
  RST_PUT(ptr, u_int64_t, l0);
  rst_endevent(ptr);
}
/* Rastro function implementation for 'l' - fortran support */
void rst_event_l_f_( int16_t *type, int64_t* l0)
{
  rst_event_l ((u_int16_t)* type, (u_int64_t)* l0);
}

void rst_init_f_(int64_t *id1, int64_t *id2)
{
  rst_init((u_int64_t)* id1, (u_int64_t)* id2);
}
void rst_finalize_f_ ()
{
  rst_finalize();
}
